replicaCount: 1

image:
  repository: secure-containers/my-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

postgres:
  host: your_db_host
  database: your_db_name
  username: your_db_username
  password: your_db_password
