apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-php-app.fullname" . }}
  labels:
    {{- include "my-php-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-php-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-php-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: my-php-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: DB_PASSWORD