apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-app.fullname" . }}-ingress
spec:
  rules:
  - http:
      paths:
      - host: 127.0.0.1.sslip.io
        path: /
        pathType: Prefix
        backend:
            service: 
              name: {{ include "my-app.fullname" . }}
              port: 
                number: {{ .Values.service.port }}