name: Publish Docker Image

on:
    push:
        branches:
            - master

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GHCR
              uses: docker/login-action@v1
              with:
                username: woodenmaiden
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5.1.0
              with:
                context: app/backend
                file: app/backend/Dockerfile
                push: true
                tags: woodenmaiden/reverse-shell-example:latest
